### ISSUE TITLE
[FR] Ansible snap

### ISSUE THREAD

**Issue by domq** [epfl-si/external-noc#15]
- En tant qu'administrateur du NOC,
- Je veux utiliser une version normalisée et conteneurisée d'Ansible et de ses dépendances,
- Mais pas avec Docker parce que [Docker c'est obsolète](https://news.ycombinator.com/item?id=16036268). Avec [snapcraft](https://snapcraft.io/) plutôt.

**Comment by domq** [comment]
@domq Wé ben [Snap ne fonctionne pas sur Mac]( https://forum.snapcraft.io/t/support-for-macos/1290) c'est pas un bon début...

**Comment by ponsfrilus** [comment]
Je crois que https://flatpak.org/ non plus... @domq

**Comment by ponsfrilus** [comment]
Fixed with https://github.com/epfl-si/ansible.suitcase/
